### ISSUE TITLE
[Bug]: To omany Recommendations

### ISSUE THREAD

**Issue by dmitrytkpn** [drafter-cloud/swipely-project#2]
### Contact Details

dmytro@swipely.io

### What happend? 
I was getting new recommendations
### Expected 
I was expect to have one pack of recommendations
### Actual 
Actually I got a 3 packs of recommendations and it is annoying me because takes too much space - so can I collapse them?
### References 
![image](https://github.com/user-attachments/assets/0de70787-a326-4afe-916d-528e10ecab2f)

### Version

latest (Google Chrome Browset)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dmitry-tuzenkov** [comment]
Fixed in version 0.8.3
