### ISSUE TITLE
[Bug]: I want to be able to login with different chromium-based browsers

### ISSUE THREAD

**Issue by dmitrytkpn** [drafter-cloud/swipely-project#4]
### Contact Details

dmytro@swipely.io

### What happened? 
I was trying to sign up with Edge
### Expected 
I was expect to be signed up usefully
### Actual 
Nothing happened so I was confused

### References 
Just be able to login with chromium but non google-chrome  authentication

### Version

latest (Other Web Browser please provide name and version)

### What browsers are you seeing the problem on?

Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dmitry-tuzenkov** [comment]
Fixed in version 0.8.3
